### ISSUE TITLE
Server responded with 0 code.

### ISSUE THREAD

**Issue by Kurtaja** [jinmingda/demo-flask-s3-dropzone#10]
Hi Jin and thank you for this compact and elegant solution!
I realize it's some years ago since you posted this, but hopefully you are still active?
I wanted to see if I could use your solution in my flask project because I find it really compact and elegant.  However, even though I'm successfully getting a presigned post from my S3 bucket, I'm not able to upload a file to it using your flask demo project. No matter what I try, I'm getting a 'Server responded with 0 code.' error (see attached image). My test file is a small 1kB text file, which I'm able to upload with Cyberduck using the same credentials as I'm using in my Flask project. 
Is your project still working in your end? (and if so, do you have any idea what it can be that causes the error I'm getting?)

![image](https://user-images.githubusercontent.com/62388983/209110241-714d002b-b38c-44af-b39d-2d4c263613f0.png)

**Comment by Kurtaja** [comment]
PS: to get past the '0 code' problem I used minio to produce the url, and that took me a bit further, though now it's crashing on the uploader.on('sending') part. See this StackOverflow post: https://stackoverflow.com/questions/74898241/upload-files-to-s3-with-flask-and-dropzone-crashes/74898257#74898257
Appreciated if you have the possibility to point me in the good direction if you see where I go wrong.
Kind regards
Kurt

**Comment by jinmingda** [comment]
Hi @Kurtaja thank you for creating the issue regarding the error you encountered. I was able to re-produce the "server responded with 0 code" error locally on my computer when the CORS is not properly configured on the destination bucket. Please see the following screenshot for details. Not sure if this is the same error that caused your problem.  

![image](https://user-images.githubusercontent.com/10823148/209725200-dab72b8b-9ea2-40b6-80b1-a6e13c644fac.png)

**Comment by Kurtaja** [comment]
Thanks @jinmingda!
I've contacted my S3 supplyer, and they confirmed that they do not support CORS yet, so that explains why I could not get it to work then. I'll let you know how it goes once they get the CORS support sorted.
