### ISSUE TITLE
how to maintain object name 

### ISSUE THREAD

**Issue by darichailu** [jinmingda/demo-flask-s3-dropzone#5]
Is this solution capable of handling large file (eg. 100GB)? Can use chucking or multipart upload method here?

**Comment by jinmingda** [comment]
@darichailu sorry for the late reply.
1. To maintain the object name, you can include the filename (not the whole file) in the request body when posting to `/get-presigned-post`. Then simply generate the presigned post with the filename as part of the S3 object key.
2. I believe you need to enable S3's multipart uploads to deal with large files. The code I put in this repo doesn't support this out of box. But you can take a look at [EvaporateJS](https://github.com/TTLabs/EvaporateJS). I have to be honest that I have never tried this library, but it looks like a viable solution after I read the documentation.

**Comment by darichailu** [comment]
Thanks for the response. I figured it out myself. For the multiparty
upload, I may have to look for other alternatives.

**Comment by darichailu** [comment]
Is there a way to do recursive folder upload,  maintaining folder and sub-folder structure? I was looking into **webkitdirectory** but not supported or non-standard.

**Comment by jinmingda** [comment]
@darichailu You are right about webkitdirectory as it is non-standard and have some compatibility issues. But other than this I couldn't find another solution either that allows recursive upload while retaining folder name. According to the [Browser compatibility report](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory), the market share for the browsers that support `webkitdirectory` is quite decent. So if you wish to proceed with `webkitdirectory`, you may just add the following code to the Dropzone constructor and access the full path by `file.webkitRelativePath`.

```js
        init: function() {
          this.hiddenFileInput.setAttribute("webkitdirectory", true);
        },
```

**Comment by darichailu** [comment]
Thanks for your reply. Have you tested the code if it worked for you?

**Comment by jinmingda** [comment]
@darichailu Yeah I tested on my Chrome and it works. I have created another branch `webkitdirectory` and a PR to demonstrate the code. What I need to point out is `webkitdirectory` will only allow you to select folders but not files in the file input field. I did some research but failed to find a solution to upload both with the same input. I'd appreciate if you can find a workaround to solve this problem.
![image](https://user-images.githubusercontent.com/10823148/90430401-3819c180-e07c-11ea-9d34-53b4dd220c63.png)

**Comment by darichailu** [comment]
@jinmingda I'll look into it and let you know what I come up with. thanks for the update

**Comment by MittalShruti** [comment]
Hi @darichailu were you able to figure chunking for browser-to-s3 upload ? a 1 GB file is taking long to upload to s3 without chunking (using dropzone)

**Comment by darichailu** [comment]
Hey, thanks for checking. I was able to do it in a different way without
using dropzone.

**Comment by MittalShruti** [comment]
Possible to share the technique? I tried browser-to-server upload and then, s3 multipart upload; which seems to be faster than direct browser upload using dropzone.

**Comment by darichailu** [comment]
I based my working solution on this project.
https://gitlab.com/jgroszko/flask-s3-multipart. You can check it out.

**Comment by MittalShruti** [comment]
Thanks! The above solution worked me.
